# Generated by Django 2.2.4 on 2020-01-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(null=True)),
                ('check_out_date', models.DateTimeField(null=True)),
                ('fecha_ingresado', models.DateTimeField(null=True)),
                ('fecha_salida', models.DateTimeField(null=True)),
                ('num_adultos', models.IntegerField(default=0)),
                ('num_ninos', models.IntegerField(default=0)),
                ('no_nights', models.IntegerField(default=0)),
                ('total_to_pay', models.FloatField(default=0)),
                ('is_removed', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='BookingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('is_removed', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('is_removed', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=200)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Habitación')),
                ('numero', models.IntegerField(verbose_name='Codigo de Habitación')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripcion de la Habitación')),
                ('path_image', models.FileField(max_length=250, upload_to='documents/', verbose_name='Subir Imagen')),
                ('calificacion', models.IntegerField(default=0, verbose_name='Calificacion')),
                ('num_camas', models.IntegerField(default=0, verbose_name='Numero de Camas')),
                ('num_adultos', models.IntegerField(default=0, verbose_name='Numero de Adultos')),
                ('num_ninos', models.IntegerField(default=0, verbose_name='Numero de Niños')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.RoomType', verbose_name='Tipo de Habitación')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('details_reason', models.TextField()),
                ('amount', models.FloatField(default=0)),
                ('is_canceled', models.BooleanField(default=False)),
                ('details_canceled', models.TextField()),
                ('is_removed', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.BookingState'),
        ),
    ]
