# Generated by Django 2.2.7 on 2020-01-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Url de Imagen')),
                ('name', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('telefono', models.CharField(max_length=250, null=True)),
                ('ciudad', models.CharField(max_length=250, null=True)),
                ('direccion', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
