# Generated by Django 2.2.7 on 2020-01-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicidad',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='dueno',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='telefono',
        ),
        migrations.AddField(
            model_name='publicidad',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='Direccion Contacto'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='Ciudad Contacto'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='company',
            field=models.CharField(default='test', max_length=100, verbose_name='Compania'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicidad',
            name='phone',
            field=models.CharField(max_length=250, null=True, verbose_name='Telefono Contacto'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='price',
            field=models.FloatField(default=100, verbose_name='Precio por Publicitar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Anuncio'),
        ),
    ]
