# Generated by Django 2.2.4 on 2020-01-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_publicidad_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='imagen',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='anuncios/', verbose_name='Url de Imagen'),
        ),
    ]
